### PR TITLE
TD-199 All courses page: поменять логику запроса к фильтрам

### PR DESCRIPTION
**Pull request by zigfrei**
#### Changes:
- removed old logic for response with pagination

### CODE REVIEW

**Comment by ReneNorth** [comment]
@zigfrei 
we don't have sorting "by default", we have "Recommended" (рекуомендуемые) that should be a default option. Could you change "by default" for "recommended"?

**Comment by zigfrei** [comment]
@ReneNorth In this case, how would you remove the sorting if a sorting filter was selected? For example, you chose the recommended sorting and then you want to remove the sorting and leave the filters?

**Comment by ReneNorth** [comment]
@zigfrei  That's a question for our designers. I think clicking a chosen sorting option should change it to a default state without any sorting. But I believe that "no sorting" should indicate the absence of applied sorting rather than being a separate option.

**Comment by zigfrei** [comment]
@ReneNorth done

**Pull request merged**
